### ISSUE TITLE
How can i reuse pretrained 

### ISSUE THREAD

**Issue by quanha72** [dat821168/bert_vn_ner#5]
At first, i admire that you guys have a great job on it, but i cant find the pretrained being used for generating the prediction. Can anyone help me about it. I'm very appreciate that
![image](https://user-images.githubusercontent.com/62066118/176344423-03e5d031-c54e-4afe-88f6-359933d24441.png)

**Comment by minhkids** [comment]
Cái này bạn đặt file output mô hình đầu ra tên là gì thì bạn phải để phần pretrain_dir giống như vậy. Ví dụ:
> python3 train.py --data_dir data/ --model_name_or_path bert-base-multilingual-cased --output_dir outputs --logs logs --cuda
thì ở phần **output**_dir là **outputs** thì ở phần predict sẽ là:
**!python3 predict.py --pretrain_dir outputs --max_seq_length 128 --batch_size 4 --cuda**

**Comment by quanha72** [comment]
Mình có thử chạy file train nhưng mà nó yêu cầu có tham số --log_dir và nó trỏ vô file vner_trainning.log, nhưng mình k có file này nên chưa chạy đc . Mình có cần phải setup gì trước khi train k v bạn ?

**Comment by datnnt1997** [comment]
> Mình có thử chạy file train nhưng mà nó yêu cầu có tham số --log_dir và nó trỏ vô file vner_trainning.log, nhưng mình k có file này nên chưa chạy đc . Mình có cần phải setup gì trước khi train k v bạn ?

After checking, I discovered that I had not updated the train command in the README after updating my source code. To train your model,  create the directory 'logs' (as an example) and run the command below.

`python3 train.py --data_dir data/ --model_name_or_path bert-base-multilingual-cased --output_dir outputs --log_dir logs --cuda`

**Comment by quanha72** [comment]
i have already tried this , but got an error about lacking of file, so where does i get this file. 
![image](https://user-images.githubusercontent.com/62066118/176615725-cb15ba1c-ac76-40b1-a717-4cd20aa9b65d.png)

**Comment by quanha72** [comment]
oh, i got it :v problem was solved. tks you guys for your support
